hypersites_store:
    resource: "@HypersitesStoreBundle/Controller/"
    type:     annotation
    prefix:   /store/

hypersites_monica:
    resource: "@HypersitesMonicaBundle/Controller/"
    type:     annotation
    prefix:   /

