hypersites_store:
    resource: "@HypersitesStoreBundle/Controller/"
    type:     annotation
    prefix:   /

hypersites_monica:
    resource: "@HypersitesMonicaBundle/Controller/"
    type:     annotation
    prefix:   /

