<?php

namespace Hypersites\MonicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
	public function getCustomerListByName()
	{

	}

	public function getCustomerByFiscalDocument()
	{

	}

	public function CustomerByEmailOrName()
	{

	}
}
